### PR TITLE
Fix for #17, plus test and connection refactor

### LINKED ISSUE #17: Rubinius error or UDP issue
I was getting an odd error using rubinius 2.2.5 and riemann-ruby-client when I started digging into it there may be an error in the UDP code.

At first the error was:
```
    NoMethodError: undefined method `bytesize' on an instance of Beefcake::Buffer.
	kernel/delta/kernel.rb:78:in `bytesize (method_missing)'
	/home/user/.rvm/rubies/rbx-2.2.5/gems/gems/rubysl-socket-2.0.1/lib/rubysl/socket.rb:1330:in `send'
```
but looking at the UDP code and how Beefcake works it looks like it is sending the Beefcake Buffer to send rather than the encoded string. From the [Beefcake docs](https://github.com/protobuf-ruby/beefcake#encoding):
``` ruby
# For example, you can encode into a String:
s = ""
x.encode(s)
s # => "\b\x01\x10\x02)\0"

# If you don't encode into anything, a new Beefcake::Buffer will be returned:
x.encode # => #<Beefcake::Buffer:0x007fbfe1867ab0 @buf="\b\x01\x10\x02)\0">

# And that buffer can be converted to a String:
x.encode.to_s # => "\b\x01\x10\x02)\0"
```

Leading me to believe that what we actually want is this:
``` ruby

require 'riemann/client'

module Riemann
  class Client
    class UDP < Client

      def send_maybe_recv(message)
        with_connection do |s|
          encoded_string = ''
          message.encode encoded_string
          unless encoded_string.length < @max_size
            raise TooBig
          end

          s.send(encoded_string, 0, @host, @port)
          nil
        end
      end
    end
  end
end

r = Riemann::Client.new
# require 'rubinius/debugger'
# Rubinius::Debugger.start
# b Riemann::Client::UDP#send_maybe_recv:1
# b UDPSocket#send:1
r << { service: 'testing', metric: 1.0, tags: ['test', 'the', 'client'] }
```

### PR DESCRIPTION
**Pull request by RKelln**
This should fix #17, all (refactored) tests pass on 1.9.3, 2.1.1, jruby-1.7.11, and rbx-2.2.6.

However when I started digging into the tests that led to all sorts of other issues that I have made separate commits for, feel free to let me know which of these you actually want, etc. This many changes make me very nervous, and I still need to try the new code in our project. Would like some confirmation that everything continues to run normally for people already using the client. 

Main changes:
 * use encoded strings everywhere instead of Beefcake Buffers
 * tests now split for TCP and UDP transport
    * some tests could not be shared because they way the original was testing was using the return value from the `<<` call so that only works with TCP transport... you should take a look and see if these should be changed to be consolidated or I screwed something up
 * `#connected?` methods are mutex locked and seemingly fixed (doesn't seem like they would have worked before?)
 * added `gemspec` and `Gemfile` to make my life easier for testing the various rubies
 * removed `Client#connect` since `tcp.connect` doesn't exist and no one was calling it

### CODE REVIEW

**Comment by aphyr** [comment]
Heya @eric, @RKelln, would you like me to merge this as-is or hold off on review?

**Comment by eric** [comment]
I'll review it now.

File: lib/riemann/client/tcp.rb [hunk 1]
```diff
@@ -63,12 +61,12 @@ def read_message(s)
             puts "Message was #{str.inspect}"
```
Comment (eric) [inline lib/riemann/client/tcp.rb]: We really should get rid of these debug messages.

File: lib/riemann/client/tcp.rb [hunk 2]
```diff
@@ -63,12 +61,12 @@ def read_message(s)
...
             raise
           end
-          
+
           unless message.ok
             puts "Failed"
```
Comment (eric) [inline lib/riemann/client/tcp.rb]: This too.

**Comment by eric** [comment]
It looks like my previous comments still need to be addressed before this is merged.

**Comment by RKelln** [comment]
Sorry, every time I'm just about to come back to this I'm stuck with some other work issue. I need to test some of Eric's suggestions.  I'd recommend the puts cleanup in another change request. Lemme see if I can squeeze in some time to finish this up this week.

**Comment by eric** [comment]
Looks great!

**Comment by aphyr** [comment]
Terrific! Thanks so much to you both. :)
